# ============================================
# Stage 1: Builder — Build the Astro site
# ============================================
FROM node:18-alpine AS builder

WORKDIR /app

# Copy dependency files first (Docker layer cache)
COPY package.json package-lock.json ./

# Install all dependencies (including devDependencies for the build)
RUN npm ci

# Copy the rest of the source code
COPY . .

# Generate the static site
RUN npm run build

# ============================================
# Stage 2: Runner — Serve with lightweight Nginx
# ============================================
FROM nginx:alpine

# Remove the default Nginx configuration
RUN rm -rf /usr/share/nginx/html/*

# Copy only the static files generated by Astro
COPY --from=builder /app/dist /usr/share/nginx/html

# Internal port (the external proxy defaults to 80)
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
